name: Run Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DEFAULT_MODEL: ${{ secrets.DEFAULT_MODEL }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with: 
        GITHUB_TOKEN: ${{ secrets.G_KEY }}
        BRANCH: gh-pages
        FOLDER: build
    
